# This workflow builds and tests svZeroDSolver. The Python version is tested on
# ubuntu and the C++ version is built and tested on different versions of
# ubuntu and macOS.
name: Buildtest
on: [push, pull_request]
jobs:
  build-ubuntu:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, ubuntu-22.04]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Install ubuntu dependencies
        run: sudo apt update && sudo apt install build-essential cmake vtk
      - name: Build svZeroDSolver
        run: |
          mkdir Release
          cd Release
          cmake -DCMAKE_BUILD_TYPE=Release ..
          cmake --build .
  build-macos:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-11, macos-12]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Install macOS dependencies
        if: ${{ matrix.os == 'macos-*' }}
        run: brew install vtk
      - name: Build svZeroDSolver
        run: |
          mkdir Release
          cd Release
          cmake -DCMAKE_BUILD_TYPE=Release ..
          cmake --build .
  