# This workflow checks for compliance with the Google C++ style guide.
name: Codechecks
on: [push, pull_request]
jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt install clang-format
      - name: Run clang-format
        run: |
          clang-format --dry-run --style=file:.clang_format --Werror src/main.cpp
